setwd("\\\\soliscom.uu.nl/uu/Users/Pronk008/MyDocuments/onderwijs/DataHandlingR")
PD1<-read.table("PatientDATA1.txt",header=TRUE,sep="")
PD2<-read.delim("PatientDATA2.txt",sep=",")
Pdata<-merge(PD1,PD2,by="PATNO",all=FALSE)
Pdata$VISIT<-as.Date(Pdata$VISIT,format="%d-%m-%Y")
Pdata$PATNO<-as.factor(Pdata$PATNO)
Pdata$AE<-as.logical(Pdata$AE)
Pdata$DX<-as.factor(Pdata$DX)
Pdata$SBP_DBP<-as.character(Pdata$SBP_DBP)
Frepl<-grep("F|f",Pdata$GENDER)
Pdata$GENDERnew<-Pdata$GENDER
Pdata$GENDERnew[Frepl]<-"Female"
Mrepl<-grep("^(M|m)",Pdata$GENDER)
Pdata$GENDERnew[Mrepl]<-"Male"
Pdata$GENDERnew<-as.factor(as.character(Pdata$GENDERnew))
table(Pdata$DX)
table(Pdata$DX,Pdata$GENDERnew)
prop.table(table(Pdata$DX,Pdata$GENDERnew))
replaceNA<-which(Pdata$HR<40)
Pdata$HR[replaceNA]<-NA
sepcol<-strsplit(Pdata$SBP_DBP,"_")
Pdata_SBP_DBP<-do.call(rbind,sepcol)
colnames(Pdata_SBP_DBP)<-c("SBP","DBP")
Pdata_SBP_DBP<-apply(Pdata_SBP_DBP,2,as.numeric)
Pdatanew<-cbind(Pdata,Pdata_SBP_DBP)
Pdatanew<-Pdatanew[,!names(Pdatanew)=="SBP_DBP"]
Pdatanew[,"diff"]<-Pdatanew$DBP-Pdatanew$SBP
Pdatanew<-Pdatanew[order(Pdatanew$HR),]
Pdatanew<-na.omit(Pdatanew)
cols<-ifelse(Pdatanew$GENDERnew=="Male","red","darkred")
par(mfrow=c(1,2))
x1<-barplot(Pdatanew$HR,col=cols,ylim=c(0,200),xlab="Patientnumber",ylab="Heartrate",names.arg=Pdatanew$PATNO)
points(Pdatanew$SBP~x1,col=cols,pch=11)
points(Pdatanew$DBP~x1,col=cols,pch=10)
legend(0,180,c("Male","Female"),col=c("red","darkred"),pch=c(15,15),cex=0.5)
legend(4,180,c("SBP","DBP"),col="black",pch=c(11,10),cex=0.5)
boxplot(Pdatanew$HR~Pdatanew$GENDERnew,col=c("darkred","red"),ylab="Heartrate")
t.test(Pdatanew$HR[which(Pdatanew$GENDERnew=="Male")],Pdatanew$HR[which(Pdatanew$GENDERnew=="Female")])
